name: xmake-CI

on:
  pull_request:
    branches: [main, dev]
    paths:
      - "xmake.lua"
      - "src/**"
      - "test/**"
      - ".github/workflows/xmake-ci.yml"
  push:
    paths:
      - "xmake.lua"
      - "src/**"
      - "test/**"
      - ".github/workflows/xmake-ci.yml"

jobs:
  backend-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 13

      - name: Set XMAKE_GLOBALDIR
        run: echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/xmake-global" >> $GITHUB_ENV

      - name: Install Xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: ".xmake-cache"

      - name: Update Xmake repo
        run: xmake repo --update

      - name: Cache packages from Xrepo
        uses: actions/cache@v3
        with:
          path: ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
          key: ${{ runner.os }}-xrepo-${{ hashFiles('**/xmake.lua') }}

      - name: Xmake config
        run: xmake config -vDy -m releasedbg --enable_test=yes

      - name: Run GTest
        run: |
          xmake build -vDy test
          xmake run test
